import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

import 'package:powerboards/ui/adaptive_text_selection_toolbar.dart';

EditableTextContextMenuBuilder? _defaultAdaptiveContextMenuBuilder(EditableTextContextMenuBuilder? contextMenuBuilder) {
  if (!powerboardsUsesSystemAdaptiveTextSelectionToolbar()) {
    return contextMenuBuilder;
  }

  return contextMenuBuilder ?? powerboardsAdaptiveInputContextMenuBuilder;
}

TapRegionCallback? _defaultAdaptiveOnPressedOutside(TapRegionCallback? onPressedOutside) {
  if (!powerboardsUsesSystemAdaptiveTextSelectionToolbar()) {
    return onPressedOutside;
  }

  return onPressedOutside ?? powerboardsAdaptiveInputOnPressedOutside();
}

class PowerboardsAdaptiveInput extends ShadInput {
  PowerboardsAdaptiveInput({
    super.key,
    super.initialValue,
    super.placeholder,
    super.controller,
    super.focusNode,
    super.decoration,
    super.undoController,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.readOnly,
    super.showCursor,
    super.autofocus,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onChanged,
    super.onEditingComplete,
    super.onSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.enabled,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.dragStartBehavior,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.onPressed,
    super.onPressedAlwaysCalled,
    TapRegionCallback? onPressedOutside,
    super.mouseCursor,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints,
    super.contentInsertionConfiguration,
    super.clipBehavior,
    super.restorationId,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    EditableTextContextMenuBuilder? contextMenuBuilder,
    super.spellCheckConfiguration,
    super.magnifierConfiguration,
    super.selectionColor,
    super.padding,
    super.leading,
    super.trailing,
    super.mainAxisAlignment,
    super.crossAxisAlignment,
    super.placeholderStyle,
    super.alignment,
    super.placeholderAlignment,
    super.inputPadding,
    super.gap,
    super.constraints,
    super.stylusHandwritingEnabled,
    super.groupId,
    super.scrollbarPadding,
    super.keyboardToolbarBuilder,
    super.top,
    super.bottom,
    super.onLineCountChange,
    super.editableTextSize,
    super.verticalGap,
  }) : super(
         contextMenuBuilder: _defaultAdaptiveContextMenuBuilder(contextMenuBuilder),
         onPressedOutside: _defaultAdaptiveOnPressedOutside(onPressedOutside),
       );
}

class PowerboardsAdaptiveInputFormField extends ShadInputFormField {
  PowerboardsAdaptiveInputFormField({
    super.id,
    super.key,
    super.onSaved,
    super.forceErrorText,
    super.validator,
    super.initialValue,
    super.enabled,
    super.autovalidateMode,
    super.restorationId,
    super.controller,
    super.label,
    super.error,
    super.description,
    super.onChanged,
    super.valueTransformer,
    super.toValueTransformer,
    super.fromValueTransformer,
    super.onReset,
    super.focusNode,
    super.decoration,
    super.placeholder,
    super.magnifierConfiguration,
    super.keyboardType,
    super.textInputAction,
    super.textCapitalization,
    super.style,
    super.strutStyle,
    super.textAlign,
    super.textDirection,
    super.autofocus,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    super.maxLines,
    super.minLines,
    super.expands,
    super.readOnly,
    super.showCursor,
    super.maxLength,
    super.maxLengthEnforcement,
    super.onEditingComplete,
    super.onSubmitted,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.cursorOpacityAnimates,
    super.cursorColor,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.keyboardAppearance,
    super.scrollPadding,
    super.enableInteractiveSelection,
    super.selectionControls,
    super.dragStartBehavior,
    super.onPressed,
    super.onPressedAlwaysCalled,
    TapRegionCallback? onPressedOutside,
    super.mouseCursor,
    super.scrollPhysics,
    super.scrollController,
    super.autofillHints,
    super.clipBehavior,
    super.scribbleEnabled,
    super.enableIMEPersonalizedLearning,
    super.contentInsertionConfiguration,
    EditableTextContextMenuBuilder? contextMenuBuilder,
    super.undoController,
    super.spellCheckConfiguration,
    super.selectionColor,
    super.padding,
    super.leading,
    super.trailing,
    super.mainAxisAlignment,
    super.crossAxisAlignment,
    super.placeholderStyle,
    super.alignment,
    super.placeholderAlignment,
    super.inputPadding,
    super.gap,
    super.constraints,
    super.groupId,
    super.keyboardToolbarBuilder,
    super.top,
    super.bottom,
    super.onLineCountChange,
    super.editableTextSize,
  }) : super(
         contextMenuBuilder: _defaultAdaptiveContextMenuBuilder(contextMenuBuilder),
         onPressedOutside: _defaultAdaptiveOnPressedOutside(onPressedOutside),
       );
}
