definitions:
  scripts:

  - &create_android_local_properties
    name: Write local.properties File
    script: |
      echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/powerboards/android/local.properties"
      echo "cmake.dir=$CM_BUILD_DIR/cmake" >> "$CM_BUILD_DIR/powerboards/android/local.properties"

  - &install_cmake
    name: Install Cmake
    script: |
      # Install CMAKE
      mkdir -p cmake
      curl -L https://github.com/Kitware/CMake/releases/download/v3.31.6/cmake-3.31.6-linux-x86_64.sh -o install-cmake.sh
      sh install-cmake.sh --skip-license --prefix=cmake

  - &setup_xcode
    name: Set up code signing settings on Xcode project
    script: |
      cd powerboards

      # flutter
      xcode-project use-profiles

      pod repo update
      

  - &fetch_deps
    name: Get Flutter Packages
    script: |
      # Install RUST
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      cd powerboards
      flutter packages pub get

workflows:

  ios-com:
    name: iOS Com
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic

    environment:
      groups:
      - sentry
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.timu.powerboards-production

      vars:
        APP_ID: 6478245491
        FLUTTER_VERSION: 3.38.4

      flutter: 3.38.4

    scripts:
    - *setup_xcode    
    - *fetch_deps

    - name: Flutter build ipa
      script: |
        cd powerboards
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
        export SENTRY_RELEASE=3.1.4+$BUILD_NUMBER
        flutter build ipa --flavor com --release --no-tree-shake-icons --build-name=3.1.4 --build-number=$BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist --dart-define-from-file=config-com.json --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE
        if [ $? -ne 0 ]; then
          echo "❌ Flutter build failed. Exiting..."
          exit 1
        fi
        export SENTRY_PROJECT=$SENTRY_PROJECT_COM
        export SENTRY_DSN=$SENTRY_DSN_COM
        flutter packages pub run sentry_dart_plugin

    artifacts:
    - powerboards/build/ios/ipa/*.ipa
    - powerboards/tmp/xcodebuild_logs/*.log
    - powerboards/flutter_drive.log

    publishing:
      email:
        recipients:
        - brandon.bethke@timu.com
        - owen.garmire@timu.com
        notify:
          success: false
          failure: false

      app_store_connect:
        auth: integration

        submit_to_testflight: true

  android-com:
    name: Android Com
    max_build_duration: 60
    instance_type: linux_x2

    scripts:
    - *create_android_local_properties
    - *install_cmake
    - *fetch_deps

    - name: Build AAB with Flutter
      script: |
        cd powerboards
        export CODEMAGIC=true
        source "$HOME/.cargo/env"
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))
        
        export SENTRY_RELEASE=3.1.$BUILD_NUMBER
        #flutter build apk --split-per-abi --build-name=3.1.$BUILD_NUMBER --build-number=$BUILD_NUMBER
        flutter build appbundle --flavor com --release --no-tree-shake-icons --build-name=3.1.$BUILD_NUMBER --build-number=$BUILD_NUMBER --dart-define-from-file=config-com.json --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE

        export SENTRY_PROJECT=$SENTRY_PROJECT_COM
        export SENTRY_DSN=$SENTRY_DSN_COM
        flutter packages pub run sentry_dart_plugin

    artifacts:
    - powerboards/build/**/outputs/**/*.apk
    - powerboards/build/**/outputs/**/*.aab
    - powerboards/build/**/outputs/**/mapping.txt
    
    publishing:

      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false

      email:
        recipients:
        - brandon.bethke@timu.com
        - owen.garmire@timu.com
        notify:
          success: false
          failure: false

    environment:
      java: 17
      groups:
      - sentry
      - google_play

      android_signing:
      - my-release-key.keystore

      flutter: 3.38.4

      vars:
        FLUTTER_VERSION: 3.38.4
        PACKAGE_NAME: "com.timu.powerboards.production"
        GOOGLE_PLAY_TRACK: alpha

  ios-life:
    name: iOS Life
    max_build_duration: 60
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: codemagic

    environment:
      groups:
      - sentry
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.timu.powerboards-prototype

      vars:
        APP_ID: 1669408238
        FLUTTER_VERSION: 3.38.4

      flutter: 3.38.4

    scripts:
    - *setup_xcode
    - *fetch_deps

    - name: Flutter build ipa
      script: |
        cd powerboards
        BUILD_NUMBER=$(($(app-store-connect get-latest-testflight-build-number "$APP_ID") + 1))
        export SENTRY_RELEASE=3.1.4+$BUILD_NUMBER
        flutter build ipa --flavor life --release --no-tree-shake-icons --build-name=3.1.4 --build-number=$BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist --dart-define-from-file=config-life.json --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE
        if [ $? -ne 0 ]; then
          echo "❌ Flutter build failed. Exiting..."
          exit 1
        fi
        export SENTRY_PROJECT=$SENTRY_PROJECT_LIFE
        export SENTRY_DSN=$SENTRY_DSN_LIFE
        flutter packages pub run sentry_dart_plugin

    artifacts:
    - powerboards/build/ios/ipa/*.ipa
    - powerboards/tmp/xcodebuild_logs/*.log
    - powerboards/flutter_drive.log

    publishing:
      email:
        recipients:
        - brandon.bethke@timu.com
        - owen.garmire@timu.com
        notify:
          success: false
          failure: false

      app_store_connect:
        auth: integration

        submit_to_testflight: true

  android-life:
    name: Android Life
    max_build_duration: 60
    instance_type: linux_x2

    scripts:
    - *create_android_local_properties
    - *install_cmake
    - *fetch_deps

    - name: Build AAB with Flutter
      script: |
        cd powerboards
        export CODEMAGIC=true
        source "$HOME/.cargo/env"
        BUILD_NUMBER=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK") + 1))

        export SENTRY_RELEASE=3.1.$BUILD_NUMBER

        #flutter build apk --split-per-abi --build-name=3.1.$BUILD_NUMBER --build-number=$BUILD_NUMBER
        flutter build appbundle --flavor life --release --no-tree-shake-icons --build-name=3.1.$BUILD_NUMBER --build-number=$BUILD_NUMBER --dart-define-from-file=config-life.json --dart-define=SENTRY_RELEASE=$SENTRY_RELEASE

        export SENTRY_PROJECT=$SENTRY_PROJECT_LIFE
        export SENTRY_DSN=$SENTRY_DSN_LIFE
        flutter packages pub run sentry_dart_plugin

    artifacts:
    - powerboards/build/**/outputs/**/*.apk
    - powerboards/build/**/outputs/**/*.aab
    - powerboards/build/**/outputs/**/mapping.txt
    
    publishing:

      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false

      email:
        recipients:
        - brandon.bethke@timu.com
        - owen.garmire@timu.com
        notify:
          success: false
          failure: false

    environment:
      java: 17      
      groups:
      - sentry
      - google_play

      android_signing:
      - my-release-key.keystore

      flutter: 3.38.4

      vars:
        FLUTTER_VERSION: 3.38.4
        PACKAGE_NAME: "com.timu.powerboards"
        GOOGLE_PLAY_TRACK: alpha
